import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@linktree/ui/toaster";
import { cn } from "@linktree/ui/cn";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "LinkTree | Mange Your Links Better",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html 
      lang="en" 
      suppressHydrationWarning
    >
      <body className={cn(
            `${geistSans.variable} ${geistMono.variable} font-sans`,
            "whitespace-pre-line overscroll-none antialiased",
          )}
        >
          <Providers>
            {children}
          </Providers>
        <Toaster />
      </body>
    </html>
  );
}
